server:
  port: 8081

spring:
  application:
    name: ghost-core

  # --- CONFIGURAÇÃO DO BANCO DE DADOS ---
  datasource:
    url: jdbc:postgresql://localhost:5432/ghost_db
    username: postgres
    password: admin # Tem que ser igual ao do docker-compose.yml
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- CONFIGURAÇÃO DE IA (CORREÇÃO DO ERRO) ---
  ai:
    # Configuração do Gemini (Google)
    google:
      genai:
        api-key: ${GEMINI_API_KEY:chave_temporaria_gemini}
        chat:
          options:
            model: gemini-1.5-flash
    
    # Configuração da OpenAI (Base para o Groq)
    openai:
      # O Spring EXIGE uma chave aqui para iniciar. Usamos uma dummy.
      api-key: sk-proj-dummy-key-for-startup 
      base-url: https://api.groq.com/openai/v1 # Já aponta para o Groq
      chat:
        options:
          model: llama3-70b-8192

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/